name : CI Check

on : 
   pull_request:
   push:
      branches:
            -main


jobs:
   verify:
      runs-on: ubuntu-latest


     steps: 
          -name: Checkout repository
           -uses: actions/checkout@v4
           -name: check README exist
            -run: test -f README.md